Add Nix configuration files and upgrade LLVM to v17.0.6 (#313)
* Add nix flake files

* Add Nix instructions to README

* Add dependencies for libs

* Clean up R build dependencies

* Update flake.nix

Co-authored-by: George Stagg <georgestagg@gmail.com>

* Remove emscripten cache in 'make clean'

* Lock to emscripten 3.1.45

* Use flang-webr nix flake

* Remove tools/flang subdirectory

* Add tools/flang submodule

* Rework EMFC make targets for LLVM Flang 17

Move EMFC and libFortranRuntime.a targets into individual fortran-*.mk
files.

Update Makefile to reflect the above change.

Update Makefile cleanup targets:
 * clean - Remove webR build tree
 * clean-wasm - Remove webR and Wasm library build tree
 * distclean - Remove webR, Wasm library, and compiler toolchain build
   tree.

* Add -fPIC to FFLAGS when building R

Fixes an issue when building with LLVM Flang 17

* Minor tweaks to Makefiles

* Update flake.nix

* Update .gitignore

* Update workflows for LLVM flang 17 and Nix

* Checkout in GHA with v4

* Handle ./configure shebang in flake.nix

* Disable Nix build sandbox in GHA

Required so that webR's build scripts may download external sources for
R and its required system libraries.

* Add clang to flake.nix build inputs

* Tweak src/Makefile for subsequent rebuilds

Fixes an issue rebuilding when `dist` has been removed.

* Upgrade to nixos-23.11

* Update NEWS.md

* Update flang-wasm submodule for LLVM v17.0.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,6 +7,9 @@ while [[ $# -gt 0 ]]; do
             USE_DRAGONEGG="true"
             shift
             ;;
+        --with-flang)
+            shift
+            ;;
         *)
             echo "Unknown argument $1"
             exit 1
@@ -16,9 +19,41 @@ done
 
 rm -f tools/fortran.mk
 
-if [ -z ${USE_DRAGONEGG-} ]
-then
-    ln -s fortran-flang.mk tools/fortran.mk
-else
+function configure_emfc {
+    EMFC_ROOT=`dirname ${EMFC}`
+    if [ -f "${FORTRAN_WASM_LIB-}" ]; then
+        EMFC_FLIB=${FORTRAN_WASM_LIB}
+    elif [ -f "${EMFC_ROOT}/../../wasm/lib/libFortranRuntime.a" ]; then
+        EMFC_FLIB=`realpath ${EMFC_ROOT}/../../wasm/lib/libFortranRuntime.a`
+    else
+        echo "Error: Can't find Fortran runtime library."
+        echo "Set FORTRAN_WASM_LIB to the location of libFortranRuntime.a,"\
+            "or unset EMFC to build LLVM flang from source."
+        exit 1
+    fi
+    echo "Found Fortran runtime library: ${EMFC_FLIB}"
+    cat << EOF > tools/fortran.mk
+EMFC = ${EMFC}
+FORTRAN_WASM_LIB = ${EMFC_FLIB}
+FORTRAN_WASM_LDADD = ${EMFC_FLIB}
+.PHONY: clean-tools
+clean-tools:
+	@
+EOF
+}
+
+if [ -n "${USE_DRAGONEGG-}" ]; then
+    # Build dragonegg from source
     ln -s fortran-dragonegg.mk tools/fortran.mk
+elif [ -n "${EMFC-}" ]; then
+    if [ -f "${EMFC-}" ]; then
+        echo "Found Fortran compiler: ${EMFC}"
+        configure_emfc
+    else
+        echo "Error: Can't find Fortran compiler, check EMFC value."
+        exit 1
+    fi
+else
+    # Build LLVM flang from source
+    ln -s fortran-flang.mk tools/fortran.mk
 fi
